theme = "catppuccin_frappe"

[editor]
color-modes = true
true-color = true
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
